name: test-functional-microshift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHONWARNINGS: ignore
  KUBECONFIG: ${{ github.workspace }}/kubeconfig
  ACCT_MGT_VERSION: "cecbe131843e5033ab6f6fdce2b5a8af58d80f9d"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Fix for "grup-efi-amd64-signed" missing
        run: |
          sudo apt-mark hold grub-efi-amd64-signed

      - name: Upgrade and install packages
        run: |
          bash ./ci/setup-ubuntu.sh

      - name: Install oc/kubectl clients
        run: |
          bash ./ci/setup-oc-client.sh

      - name: Install Keycloak
        run: |
          bash ./ci/setup-keycloak.sh

      - name: Install Microshift
        run: |
          ./ci/microshift.sh

      - name: Install ColdFront and plugin
        run: |
          ./ci/setup.sh

      - name: Run functional tests
        run: |
          ./ci/run_functional_tests_openshift.sh
